name: Typescript abstractions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['abstractions/typescript/**', '.github/workflows/**']
  pull_request:
    paths: ['abstractions/typescript/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./abstractions/typescript
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - run: npm ci
        working-directory: ${{ env.relativePath }}
      - run: npm run build
        working-directory: ${{ env.relativePath }}
      # - run: npm run test
      #   working-directory: ${{ env.relativePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/dist/
            ${{ env.relativePath }}/.npmignore
            ${{ env.relativePath }}/README.md
            ${{ env.relativePath }}/package.json
            ${{ env.relativePath }}/package-lock.json
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_GH_TOKEN }}" > .npmrc
      - run: npm publish
      - run: rm .npmrc
        if: always()
