name: Publish Dotnet tool
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']
    paths: ['src/**', '.github/workflows/**']
jobs:
  push_to_feed:
    env:
      relativePath: ./src/kiota
    environment:
      name: staging_feeds
    name: Push tool to GitHub packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore kiota.csproj
        working-directory: ${{ env.relativePath }}
      - name: Build
        run: dotnet build kiota.csproj --no-restore -c Release
        working-directory: ${{ env.relativePath }}
      - name: Pack
        run: dotnet pack kiota.csproj --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/nupkg/*.nupkg
      - run: dotnet nuget push "${{ env.relativePath }}/nupkg/*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/microsoft/index.json -k ${{ secrets.PUBLISH_GH_TOKEN }}
